In [12]:
import pandas as pd
import numpy as np
df=pd.read_csv('inaturalistpoints_2088902879760696442.csv')
df_cleaned=df.dropna()
df_aedes=df_cleaned.loc[df_cleaned['ObsTaxonName']=='Aedes aegypti']
import re
month=[]
day=[]
year=[]
for i in range(len(df_aedes)):
    data_string=df_aedes['observationResCatObsPheTime'].values[i]
    matches = re.findall(r'\d+', data_string)  # Find all numbers
    month.append(int(matches[0]))
    day.append(int(matches[1]))
    year.append(int(matches[2]))
day=np.array(day)
month=np.array(month)
year=np.array(year)
df_aedes.insert(0,'day',day)
df_aedes.insert(1,'month',month)
df_aedes.insert(2,'year',year)
columns_list=['day','month','year','ObsTaxonName','latitude','longitude']
df_aedes_inaturalist=df_aedes.loc[:,columns_list]
df_aedes_inaturalist

        day  month  year   ObsTaxonName   latitude   longitude
189      17      5  2024  Aedes aegypti  22.372626  114.113530
265       7      5  2024  Aedes aegypti  33.911454  -98.493129
587       5      5  2024  Aedes aegypti -20.760947  -42.869286
588       6      5  2024  Aedes aegypti -22.566321   17.088146
590      28      4  2024  Aedes aegypti  29.548858  -98.706295
...     ...    ...   ...            ...        ...         ...
130572   28      4  2021  Aedes aegypti -31.655230  -60.724008
130577   23      4  2021  Aedes aegypti  26.436739  -82.125718
130615   15     12  2020  Aedes aegypti -15.799360  -47.809470
130674   12     12  2020  Aedes aegypti -22.929475  -43.391664
130716   20      3  2019  Aedes aegypti  18.260519  -65.800158

[4365 rows x 6 columns]

In [14]:
import pandas as pd
import numpy as np
df_mosquito_alert=pd.read_csv('mosquitoAlert_2750354792241070964.csv')
df_aedes=df_mosquito_alert.loc[df_mosquito_alert['Indentified by Human']=='Aedes aegypti']
import re
month=[]
day=[]
year=[]
for i in range(len(df_aedes)):
    data_string=df_aedes['observationResCatObsPheTime'].values[i]
    matches = re.findall(r'\d+', data_string)  # Find all numbers
    month.append(int(matches[0]))
    day.append(int(matches[1]))
    year.append(int(matches[2]))
day=np.array(day)
month=np.array(month)
year=np.array(year)
df_aedes.insert(0,'day',day)
df_aedes.insert(1,'month',month)
df_aedes.insert(2,'year',year)
columns_list=['day','month','year','Indentified by Human','latitude','longitude']
df_aedes_mosquito_alert=df_aedes.loc[:,columns_list]
df_aedes_mosquito_alert

        day  month  year Indentified by Human   latitude  longitude
1251     22     11  2019        Aedes aegypti  18.648960  -91.83176
1537     31     10  2019        Aedes aegypti  18.440850  -69.97596
2094      8      1  2019        Aedes aegypti  18.360130  -66.06963
3005      6     11  2018        Aedes aegypti  34.049560 -118.21090
3046      5     11  2018        Aedes aegypti  34.049530 -118.21100
3214      4     10  2019        Aedes aegypti  18.885040  -99.22128
3231     31     10  2018        Aedes aegypti  14.028260  -87.22404
4070     29      8  2019        Aedes aegypti  20.653120 -103.37590
5446     11      4  2018        Aedes aegypti  -8.106552  -79.03483
5995     19      3  2018        Aedes aegypti  -8.106637  -79.03434
5999     19      3  2018        Aedes aegypti  -8.106465  -79.03456
6011     18      3  2018        Aedes aegypti  -8.106528  -79.03473
6016     18      3  2018        Aedes aegypti  -8.106513  -79.03471
6021     18      3  2018        Aedes aegypti  -8.106528  -79.03471
6134      8      3  2018        Aedes aegypti  -8.109658  -79.03580
6142      7      3  2018        Aedes aegypti  -8.106419  -79.03461
6153      7      3  2018        Aedes aegypti  -8.106463  -79.03467
9411      2      5  2017        Aedes aegypti  -8.106497  -79.03459
9417      2      5  2017        Aedes aegypti  -8.106497  -79.03459
10370    20      6  2017        Aedes aegypti  -8.109578  -79.03581
10468    21      6  2016        Aedes aegypti  14.522150  -90.55454
10612    17      6  2017        Aedes aegypti  -8.106462  -79.03465
14208    24      7  2016        Aedes aegypti  31.507630   74.32375
14272    24      7  2016        Aedes aegypti  31.507700   74.32355
22623    19      7  2020        Aedes aegypti  34.049680 -118.21120
27321    21      4  2020        Aedes aegypti -26.836820  -65.23828
29082    15      1  2020        Aedes aegypti  12.066130  -68.85168
31411     4     10  2021        Aedes aegypti  19.354470  -99.08892
38018     7      9  2021        Aedes aegypti  18.330920  -66.40660
39621     6      9  2021        Aedes aegypti  12.134330  -68.90984
39657     6      9  2021        Aedes aegypti  12.134320  -68.90980
40154     6      9  2021        Aedes aegypti  12.151390  -68.97049
40928    11      8  2021        Aedes aegypti  12.150520  -68.97137
44407     8      8  2021        Aedes aegypti  27.206170   77.88740
65928    21      5  2021        Aedes aegypti  18.520790   73.83964
70098    13      1  2021        Aedes aegypti  10.056460  -69.28896
71792    18     10  2022        Aedes aegypti  33.592680 -117.71250
72899     8     10  2022        Aedes aegypti  12.151410  -68.97041
82856    12      7  2022        Aedes aegypti  19.704710 -101.18790
83824    14      7  2022        Aedes aegypti  25.684000  -80.33884
88269    23      6  2022        Aedes aegypti  20.570860 -103.48480
93453     6      6  2022        Aedes aegypti  19.704590 -101.18780
97728     3      3  2022        Aedes aegypti  20.971270  -89.62160
100133   27     12  2023        Aedes aegypti -32.699520  -57.61998
100770   28     11  2023        Aedes aegypti  28.093290  -15.48560
101916   24     11  2023        Aedes aegypti  32.638390  -16.94634
119540   22      8  2023        Aedes aegypti   6.316444  -73.95121
125200    8      8  2023        Aedes aegypti  28.002290  -82.75266
136607   18      7  2023        Aedes aegypti  27.933870  -82.74132
172917   30      4  2023        Aedes aegypti  38.882230  -76.99493
175123    2      5  2023        Aedes aegypti  -0.986004  -77.83169
175265   11      2  2023        Aedes aegypti   2.734864   73.00813
176445   25      2  2023        Aedes aegypti   2.667367   72.89268
176786   24      1  2023        Aedes aegypti -34.587420  -58.40289
176800   24      1  2023        Aedes aegypti -15.365790  -44.25777

In [15]:
df_joint=pd.concat([df_aedes_inaturalist,df_aedes_mosquito_alert],axis=0,ignore_index=True)
df_joint['Specie']=df_joint['ObsTaxonName'].str.cat(df_joint['Indentified by Human'],sep=' ',na_rep=' ')
df_joint_specie=df_joint.drop(columns=['ObsTaxonName','Indentified by Human'])
df_joint_specie

      day  month  year   latitude   longitude           Specie
0      17      5  2024  22.372626  114.113530  Aedes aegypti
1       7      5  2024  33.911454  -98.493129  Aedes aegypti
2       5      5  2024 -20.760947  -42.869286  Aedes aegypti
3       6      5  2024 -22.566321   17.088146  Aedes aegypti
4      28      4  2024  29.548858  -98.706295  Aedes aegypti
...   ...    ...   ...        ...         ...              ...
4415    2      5  2023  -0.986004  -77.831690    Aedes aegypti
4416   11      2  2023   2.734864   73.008130    Aedes aegypti
4417   25      2  2023   2.667367   72.892680    Aedes aegypti
4418   24      1  2023 -34.587420  -58.402890    Aedes aegypti
4419   24      1  2023 -15.365790  -44.257770    Aedes aegypti

[4420 rows x 6 columns]

In [16]:
df_joint_specie.to_csv('GMOD_database_aegypti.csv')